[pytest]
testpaths = testcases
python_files = test_*.py *_test.py Test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    -s
    --tb=short
    --alluredir=allure-results
    --clean-alluredir
    --self-contained-html
    --capture=no
    --strict-markers
    --disable-warnings
    --headed
    --tracing=on
    ; --count=3

markers =
    regression: Regression test suite
    smoke: Smoke test suite